### ISSUE TITLE
colorTuner not working

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/ColorTuner#8]
Hi! 

During my process of updating drone exercises, I am having problems with colorTuner tool. The following image shows the error that I'm getting:

![colorTuner](https://user-images.githubusercontent.com/35956525/73649604-70c5f080-4680-11ea-9028-d9ac1cbecfc1.png)

I'm working with Ubuntu 18.04, ROS Melodic, gazebo9 and jderobot-base/assets.

Thanks!

**Comment by pankhurivanjani** [comment]
Hello @pariaspe !
Currently, the ros-package release of this tool is in progress, so you are not able to use it directly.  

But don't worry we have the workaround to use this tool is:
1. Download this github repository (git clone) 
2. cd ColorTuner
3. source /opt/ros/melodic/setup.bash 
4. python colorTuner.py colorTuner_py.yml 

You might require to change the config file parameters according to different exercises, so take care of that :) 
I will edit the cmakelist for direct install and we are working on ros-package release.

**Comment by pariaspe** [comment]
Hi @pankhurivanjani !
The error still persists with the workaround. Any idea what is happening with `kobuki_msgs`?

Thanks!

**Comment by pankhurivanjani** [comment]
Hey! This is not the error with ColorTuner tool then probably if you can give more information I can look into the issue.
It's working with the laptop camera, did you change the ros topic in configuration topic?

**Comment by jmplaza** [comment]
Yeah, that's weird. ColorTuner it is not related with any kobuki msg... It only uses (or should use) camera related ROS topics, and Kobuki mesgs are for the kobuki robot

**Comment by pariaspe** [comment]
> Hey! This is not the error with ColorTuner tool then probably if you can give more information I can look into the issue.
> It's working with the laptop camera, did you change the ros topic in configuration topic?

I did not change anything, should I do it?

**Comment by pankhurivanjani** [comment]
Yes, The ros topic which this tool is subscribing to currently is the usb camera driver. For drone exercises the appropriate topic should be put in the yaml file

**Comment by pankhurivanjani** [comment]
Hi @pariaspe , are you still facing issues with the tool or should I close the issue now?

**Comment by pariaspe** [comment]
Yes, sorry for the stale issue.
